services:
    gem_security.kernel.controller:
        class: Gem\SecurityBundle\EventListener\ControllerListener
        tags:
          - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}
