Gem\SystemBundle\Entity\Actions:
    type: entity
    table: actions
    indexes:
        FK_actions:
            columns:
                - modifiedby
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        lastmodified:
            type: datetime
            nullable: true
        isdeleted:
            type: smallint
            nullable: true
            options:
                unsigned: false
                default: '0'
    manyToOne:
        modifiedby:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                modifiedby:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
